# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

""""Symbols that should have their API docs generated by stardoc

This differs from :index.bzl because we don't have wrapping macros that hide the real doc"""

# image
# bundle
# import
# load
# pull
# push
load(
    "//container:image.bzl",
    "container_image_",
    # "container_bundle",
    # "container_import",
    # "container_load",
    # "container_pull",
    # "container_push",
)

container_image = container_image_
# ANY RULES ADDED HERE SHOULD BE DOCUMENTED, run yarn stardoc to verify
