# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

""""Symbols that should have their API docs generated by stardoc

This differs from :index.bzl because we don't have wrapping macros that hide the real doc"""

load(
    "//container:container.bzl",
    _container_bundle="container_bundle",
    _container_import="container_import",
    _container_load="container_load",
    _container_pull="container_pull",
)
load(
    "//container:image.bzl",
    _container_image="container_image_",
)
load(
    "//container:layer.bzl",
    _container_layer="container_layer_",
)
load(
    "//container:push.bzl",
    _container_push = "container_push",
)

container_layer = _container_layer
container_image = _container_image
container_bundle = _container_bundle
container_import = _container_import
container_load = _container_load
container_pull = _container_pull
container_push = _container_push
