name: release



on:
  push:
    tags: 
    - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux_amd64
          - linux_arm64
          - linux_s390x
          - darwin_amd64
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -LO bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64
          chmod +x bazelisk
          ./bazelisk build --platforms=@io_bazel_rules_go//go/toolchain:${{ matrix.platform }} //container/go/cmd/puller:puller //container/go/cmd/loader:loader
